apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: argo-demo
  namespace: default
spec:
  components:
  - name: argo-demo
    type: argo-app
    properties:
      Application:
        metadata:
          name: argo-demo
          annotations:
             argocd-image-updater.argoproj.io/image-list: demo=qms19/web-demo
             argocd-image-updater.argoproj.io/demo.kustomize.image-name: qms19/web-demo
             argocd-image-updater.argoproj.io/write-back-method: git
        spec:
          source: 
            repoURL: https://github.com/qms19/gitops-example.git
            targetRevision: main
            path: apps
          # destination:
          #   namespace: "default"
          #   server: "https://kubernetes.default.svc"
          project: "default"
